### ISSUE TITLE
what does `the essential parts of QuantLib` mean, exactly?

### ISSUE THREAD

**Issue by shrektan** [eddelbuettel/rcppquantuccia#3]
I know it's not a good place to ask such questions, but since there's no mailling-list for this package... I don't know where is suitable to ask... So apologize in advance.

The header-only `quantlib` is appealing to me that it avoid the problem to install `quantlib` and we can use Rcpp to calculate some numbers via C++ in R directly.

However, after exploring the `include` folder, I couldn't find anything about pricing the fixed income or other instruments, which makes me frustrated on what `the essential parts of QuantLib` means...

Thanks.

**Comment by eddelbuettel** [comment]
Why don't you ask @pcaspers ?

**Comment by shrektan** [comment]
ok~

**Comment by eddelbuettel** [comment]
In a nutshell, it is what we make it. I was so far interested mostly in calendaring, not pricing.

We can probably carry some more things over, but it should probably happen over there first.

**Comment by shrektan** [comment]
Yeah, I get it. Thank you very much 👍
